language: node_js
dist: bionic
sudo: required

node_js:
    - 10
    - 12

services:
    - postgresql

env:
    global:
        - PGUSER=postgrator
        - PGPASSWORD=postgrator
        - PGDATABASE=postgrator
        - PGPORT=5432

before_script:
    - psql -c 'create database postgrator' -U postgres
    - psql -c 'create role postgrator' -U postgres
    - psql -c 'grant all privileges on database postgrator to postgrator'

script:
    - psql -c "SELECT version();"
    - npm run test
