language: node_js
dist: bionic
sudo: required

node_js:
    - 6
    - 10
    - 12

services:
    - postgresql

before_script:
    - psql -c 'create database postgrator'
    - psql -c 'create role postgrator'
    - psql -c 'alter role postgrator with login'
    - psql -c 'alter role postgrator with encrypted password $$postgrator$$'
    - psql -c 'grant all privileges on database postgrator to postgrator'

script:
    - psql -c "SELECT version();"
    - npm run test
